permalink: pretty
url: "http://jeaye.com"
# TODO: Remove remaining instances
resource_url: "http://jeaye.com"

# TODO: Meta keywords in header
# TODO: Remove dependency on blog css

markdown: redcarpet
highlighter: pygments
exclude: [.bundle, vendor]
