gems:
  - octopress-minify-html

permalink: pretty
home_url: "https://jeaye.com"
blog_url: "https://blog.jeaye.com"
url: "https://jeaye.com"
license_url: "https://github.com/jeaye/jeaye.com/blob/gh-pages/LICENSE"

# TODO: Setup a nice font
sass:
  sass_dir: css-partial
  style: compressed

highlighter: rouge
exclude: [.bundle, vendor, Gemfile, Gemfile.lock, node_modules, img-partial, css-partial, generate-sprite-sheet, run, publish, blog]
