defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "jeaye"
      layout: "default"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      author: "jeaye"
      layout: "default"

permalink: pretty
url: "http://jeaye.com"
# TODO: Remove remaining instances
resource_url: "http://jeaye.com"

# TODO: Meta keywords in header
# TODO: Remove dependency on blog css

markdown: redcarpet
highlighter: pygments
exclude: [.bundle, vendor]
