permalink: pretty
url: "http://jeaye.com"
blog_url: "http://blog.jeaye.com"

# TODO: Remove dependency on blog css
# TODO: Add as blog submodule

markdown: redcarpet
highlighter: pygments
exclude: [.bundle, vendor]
