gems:
  - jekyll-assets

permalink: pretty
home_url: "https://jeaye.com"
blog_url: "https://blog.jeaye.com"
url: "https://jeaye.com"
license_url: "https://github.com/jeaye/jeaye.com/blob/gh-pages/LICENSE"

# TODO: Remove dependency on blog css

highlighter: rouge
exclude: [.bundle, vendor]
