defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "jeaye"
      layout: "default"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      author: "jeaye"
      layout: "default"

permalink: pretty
url: "http://jeaye.com"
resource_url: "http://jeaye.com"

markdown: redcarpet
highlighter: pygments
exclude: [.bundle, vendor]
